Repository GuilhermeStracini/apiclient-boilerplate-dotnet, pull requests merged in 2025-02, with the labels that each got.

#305 Update infisical-secrets-check.yml
  .github/workflows/infisical-secrets-check.yml
Labels: enhancement, size/XS, ☑️ auto-merge, Review effort [1-5]: 1

#306 [CI] Skip SonarCloud analysis for pull requests from forks
  .github/workflows/sonarcloud.yml
Labels: enhancement, size/S, ☑️ auto-merge, Review effort [1-5]: 2

#304 Fix: Prevent coverage upload on forked PRs in AppVeyor
  appveyor.yml
Labels: enhancement, Review effort [1-5]: 2
